include:
  template: Dependency-Scanning.gitlab-ci.yml

image: node:12

pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv dist public
  artifacts:
    paths:
    - public
  only:
  - master
